export const GET_DATA_TABLE = "GET_DATA_TABLE";
export const BOOK_TABLE = "BOOK_TABLE";
export const ON_CHANGE_LANGUAGE = "ON_CHANGE_LANGUAGE";
export const GET_LANGUAGE_TRANSLATE = "GET_LANGUAGE_TRANSLATE";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
